export const FETCH_USERS_LIST_REQUEST = "FETCH_USERS_LIST_REQUEST";
export const FETCH_USERS_LIST_SUCCESS = "FETCH_USERS_LIST_SUCCESS";
export const FETCH_USERS_LIST_FAILURE = "FETCH_USERS_LIST_FAILURE";